version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: code-editor-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: code-editor-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock   # backend needs access to Docker
    environment:
      - MONGO_URI=mongodb://mongo:27017/codeeditor
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: code-editor-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # persistent Mongo storage

  mongo-express:
    image: mongo-express:latest
    container_name: code-editor-mongo-express
    restart: always
    ports:
      - "8081:8081"   # Web UI at http://localhost:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo

volumes:
  mongo_data:
